In [1]:
import pandas as pd

In [7]:
LINK = './mtcars.csv'
df = pd.read_csv(LINK)
df.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [13]:
# 1사분위, 2자리 반올림
q1 = df['mpg'].quantile(0.25)
print(round(q1, 2))

15.42

In [27]:
# 조건문 19 ~ 21
cond1 = df['mpg'] >= 19
cond2 = df['mpg'] <= 21
df[~ cond1 & cond2][['model', 'mpg']]

                  model   mpg
4     Hornet Sportabout  18.7
5               Valiant  18.1
6            Duster 360  14.3
10            Merc 280C  17.8
11           Merc 450SE  16.4
12           Merc 450SL  17.3
13          Merc 450SLC  15.2
14   Cadillac Fleetwood  10.4
15  Lincoln Continental  10.4
16    Chrysler Imperial  14.7
21     Dodge Challenger  15.5
22          AMC Javelin  15.2
23           Camaro Z28  13.3
28       Ford Pantera L  15.8
30        Maserati Bora  15.0

In [ ]:
# IQR 구하기
Q3 = df['hp'].quantile(0.75)
Q1 = df['hp'].quantile(0.25)
IQR = Q3 - Q1
print(IQR)

83.5

In [38]:
# wt 변수의 상위 10개 값의 총 합
top10 = df.sort_values('wt', ascending=False)
sum_top10 = sum(top10['wt'].head(10))
print(int(sum_top10))

42

In [ ]:
# 전체 차 중 cyl의 6의 비율, 첫째자리
cond = df['cyl'] == 6
val = len(df[cond]['cyl'])
total = len(df)

print(round( val / total, 1))

0.2

In [49]:
# 10개 mpg 열 평균값 반올림 정수
mean10 = df['mpg'].loc[:9].mean()
round(mean10)

20

In [51]:
LINK = "https://raw.githubusercontent.com/Datamanim/datarepo/main/youtube/youtube.csv"
df = pd.read_csv(LINK, index_col=0)
df.head()

,title,channelTitle,categoryId,view_count,likes,dislikes,comment_count,channelId,trending_date2
0,[신병] 물자창고,장삐쭈,23,1893473,38249,730,8595,UChbE5OZQ6dRHECsX0tEPEZQ,2021-01-01
1,RAIN(비) - 나로 바꾸자 Switch to me (duet with JYP) MV,RAIN's Official Channel,10,2600864,0,0,20129,UCxXgIeE5hxWxHG6dz9Scg2w,2021-01-01
2,2020년 제야의 종 온라인 타종행사 | 보신각 현장 행사는 진행하지 않습니다.,서울시 · Seoul,29,347049,3564,120,178,UCZUPZW5idAxYp-Asj__lVAA,2021-01-01
3,고기남자의 칠면조 파티,고기남자 MeatMan,26,528458,15372,280,3470,UCT3CumbFIJiW33uq0UI3zlg,2021-01-01
4,골목 3mc를 분노하게 만든 마음고생이 심했을 공릉 백반집 사장님의 푸념?! [예능...,스브스밥집,24,494904,3918,111,3142,UCdWgRSfttvDucq4ApcCg5Mw,2021-01-01

In [ ]:
df.groupby('channelId').size().sort_values()

channelId
UC-0229MiVYnQoUxdLJnFl_g     17
UC-0C8yVGJy-cS4FGlYKelWw    138
UC-0tICWyA0_AJAVMBHL8GdQ     12
UC-2Y8dQb0S6DtpxNgAKoJKA      7
UC-5acDjU6XFWu-__G17V_YQ     20
                           ...
UCznImSIaxZR7fdLCICLdgaQ     10
UCzt24ffdUiJvJAm5HY084aw     22
UCzteSXznVjwESizsCcSKSWw      7
UCzxXBQnJy9guqVNM6KXi0Ig     10
UCzz58-H0wzmGoFi3MO_9ePQ    102
Length: 1770, dtype: int64

In [ ]:
# dislikes > likes 인 channelTitle 모두 출력
list(df['channelTitle'][df['dislikes'] > df['likes']].unique())

['핫도그TV',
 'ASMR 애정TV',
 '하얀트리HayanTree',
 '양팡 YangPang',
 '철구형 (CHULTUBE)',
 '왜냐맨하우스',
 '(MUTUBE)와꾸대장봉준',
 '오메킴TV',
 '육지담',
 'MapleStory_KR',
 'ROAD FIGHTING CHAMPIONSHIP',
 '사나이 김기훈',
 '나혼자산다 STUDIO',
 'Gen.G esports']

In [ ]:
# channelTitle(변경가능), channelId(변경불가) 인데 title 바꾼 채널 갯수
change_count = df.groupby('channelId')['channelTitle']

In [75]:
change_count = df.groupby('channelId')['channelTitle'].nunique() - 1

In [79]:
change_count = df.groupby('channelId')['channelTitle'].nunique() - 1

# 변경된 채널 필터링
changed_channels = change_count[change_count > 0]

# 변경된 채널 ID 리스트
changed_channel_names = changed_channels.index.tolist()

# 변경된 채널 수와 이름 출력
changed_channels_count = len(changed_channels)
changed_channel_names, changed_channels_count

(['UC-IYpdOqjkER7B6cnChwlhA',
  'UC0PsUG07plnP_uQQS9djFVQ',
  'UC2KUewlF-PdkGukAOI-sTqw',
  'UC2PSaEnLp6pyqFCvYvhrZmw',
  'UC3IZKseVpdzPSBaWxBxundA',
  'UC4LW3sOslC14Vn5bcoNUBkg',
  'UC4nEQI74rZkFKlUSwi0ur4A',
  'UC5RIONX9G_2zb_x4SRJgBbQ',
  'UC5b2_GAScxz4guty7rv4Ulg',
  'UC6lNIbU1SSA9YjveOx9a_oA',
  'UC8AD5KHdsFzp8qoJvS4YSYg',
  'UC8OUSYm-ztRAT6EE6VHPpGw',
  'UC98TOxKQk4aLcx0EjIK0LkQ',
  'UC9mpnu1x96y7utLpnYyU6kw',
  'UC9w-h_ciMmX64TcLRcb1xPg',
  'UCAySceX4rbSr408F1dUpuUw',
  'UCC1LvVTX2ySKYjeIXkAtvsQ',
  'UCDih-87kuRMA8uFcrx10Wlw',
  'UCEqMMsgBKhJXoeTX8buLm7g',
  'UCF8W68PS2Ltz17lTDSptDvg',
  'UCGv8eaHcDr4mRsL-bSFzGjg',
  'UCHBvfByzuzamrZiL398jopQ',
  'UCINRJxfiq8pXfQm1EucWFfw',
  'UCIn1p2ZbhOo8fyZp1S60uGg',
  'UCKHLAo7XoeP5s2GhCC75uGA',
  'UCKp8knO8a6tSI1oaLjfd9XA',
  'UCLynj-ec93et1z_SU0PM6_A',
  'UCPhHBEtG6dVZ5fJKoNArcJw',
  'UCRDowcnvz5ZVh-3NVAdfiqg',
  'UCSiGNrrL2lAc0-_MfcUUUHA',
  'UCUEX0L7GHPs95m8S7G6kWVA',
  'UCVWr5QkOkYupX6fEELMNvuQ',
  'UCY2wHBgv2W30w6lqoLxq99g',
  'UCYeeEwH_s9yD9HQe4e2JuBw',
  'UCaZS_XwAu1yBMNoQDD1mR7g',
  'UCdpbqw5DPdBfaeByMF2Re0g',
  'UCed3O-T9sAYz3ICY7IHtZuA',
  'UCefN2fe9ZDj16yTHM9dgaXA',
  'UCepUWUpH45hRTi-QePdq1Bg',
  'UCg8U-ZpbO8V4kpAlZjqtVqg',
  'UCgiO7Kxib0SZEG0DoeuBkdQ',
  'UChK2DhvPSG3sY0jIYYngVBA',
  'UChg51lDUTR_8zWeNewdxaNw',
  'UCiBKp3KgsQCYT9Z2XxdBpbQ',
  'UCiEEF51uRAeZeCo8CJFhGWw',
  'UCjO3ji06DxmTM1RrzLVwmkA',
  'UCk5bhZYNtbPJyNLRxN8D8NQ',
  'UCkjk77yUtLnuSalpGrlrG2Q',
  'UCl0HemfAt7dShJRf59_cuGQ',
  'UCl23-Cci_SMqyGXE1T_LYUg',
  'UCmA7038F43v888Q82sNTNCw',
  'UCmgt7ewcg_HscfA4ks7rGhg',
  'UCms8Ge7H1ZGgw6nV94fUhUQ',
  'UCn64fSqF2l4rkkjtQUpku2A',
  'UCn_38aaCktkBLPv3EtfmiUA',
  'UCnx4Fi4cmkLGDiFfZ311wWw',
  'UCqHP70746lwBPFp30_wl5gQ',
  'UCrFlv9c4LItVlIMCC2p6LOg',
  'UCs8R3nVeg0E100H6C8qozgw',
  'UCt8iRtgjVqm5rJHNl1TUojg',
  'UCtQYhzJWFai1y30UIA3uwYQ',
  'UCtfGLmp6xMwvPoYpI-A5Kdg',
  'UCuKdaTsJ9Jv94hVV_I9aRxQ',
  'UCudezj2i6R94QOPqGJhbZwg',
  'UCvCGySUWvTiklygO4QlXRWQ',
  'UCxLc0zV-d2elxan2nc2xRCA',
  'UCxQXvvaqwA2NzPXs5775ogw',
  'UCx_kYu6Wp1yxZP_KtrW52EQ',
  'UCytBYTjlE45XxrJ7SxO2igg',
  'UCz0F9ndJTA0eL2XyL5R8YNg',
  'UCzay0uHEiaSsKmuGkCg-mSg'],
 71)