In [6]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/youtube/youtube.csv",index_col=0)
df.head()

,title,channelTitle,categoryId,view_count,likes,dislikes,comment_count,channelId,trending_date2
0,[신병] 물자창고,장삐쭈,23,1893473,38249,730,8595,UChbE5OZQ6dRHECsX0tEPEZQ,2021-01-01
1,RAIN(비) - 나로 바꾸자 Switch to me (duet with JYP) MV,RAIN's Official Channel,10,2600864,0,0,20129,UCxXgIeE5hxWxHG6dz9Scg2w,2021-01-01
2,2020년 제야의 종 온라인 타종행사 | 보신각 현장 행사는 진행하지 않습니다.,서울시 · Seoul,29,347049,3564,120,178,UCZUPZW5idAxYp-Asj__lVAA,2021-01-01
3,고기남자의 칠면조 파티,고기남자 MeatMan,26,528458,15372,280,3470,UCT3CumbFIJiW33uq0UI3zlg,2021-01-01
4,골목 3mc를 분노하게 만든 마음고생이 심했을 공릉 백반집 사장님의 푸념?! [예능...,스브스밥집,24,494904,3918,111,3142,UCdWgRSfttvDucq4ApcCg5Mw,2021-01-01

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 60399 entries, 0 to 60398
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           60399 non-null  object
 1   channelTitle    60399 non-null  object
 2   categoryId      60399 non-null  int64
 3   view_count      60399 non-null  int64
 4   likes           60399 non-null  int64
 5   dislikes        60399 non-null  int64
 6   comment_count   60399 non-null  int64
 7   channelId       60399 non-null  object
 8   trending_date2  60399 non-null  object
dtypes: int64(5), object(4)
memory usage: 4.6+ MB

In [ ]:
# 조회수(view_count) 상위 5개 동영상 조회
df.sort_values('view_count', ascending=False).head(5)

,title,channelTitle,categoryId,view_count,likes,dislikes,comment_count,channelId,trending_date2
30583,BTS (방탄소년단) 'Butter' Official MV,HYBE LABELS,10,296314174,16464253,181350,6939302,UC3IZKseVpdzPSBaWxBxundA,2021-06-04
30383,BTS (방탄소년단) 'Butter' Official MV,HYBE LABELS,10,292502967,16413537,178381,6913277,UC3IZKseVpdzPSBaWxBxundA,2021-06-03
30174,BTS (방탄소년단) 'Butter' Official MV,HYBE LABELS,10,289350312,16369715,175204,6889393,UC3IZKseVpdzPSBaWxBxundA,2021-06-03
29964,BTS (방탄소년단) 'Butter' Official MV,HYBE LABELS,10,285698612,16319755,172331,6864694,UC3IZKseVpdzPSBaWxBxundA,2021-06-02
29729,BTS (방탄소년단) 'Butter' Official MV,HYBE LABELS,10,282265069,16272565,168794,6845770,UC3IZKseVpdzPSBaWxBxundA,2021-06-02

In [15]:
# 평균 좋아요(likes) 반올림 계산
round(df['likes'].mean())

78471